In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("bengaluru_house_prices.csv")
df['location'] = df['location'].str.lower()
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,electronic city phase ii,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,chikka tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,richards town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,raja rajeshwari nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [3]:
df.groupby('area_type')['area_type'].count()

area_type
Built-up  Area          2418
Carpet  Area              87
Plot  Area              2025
Super built-up  Area    8790
Name: area_type, dtype: int64

In [4]:
df2=df.drop([ 'society', 'balcony', 'availability','area_type'], axis='columns')
df2

                       location       size total_sqft  bath   price
0      electronic city phase ii      2 BHK       1056   2.0   39.07
1              chikka tirupathi  4 Bedroom       2600   5.0  120.00
2                   uttarahalli      3 BHK       1440   2.0   62.00
3            lingadheeranahalli      3 BHK       1521   3.0   95.00
4                      kothanur      2 BHK       1200   2.0   51.00
...                         ...        ...        ...   ...     ...
13315                whitefield  5 Bedroom       3453   4.0  231.00
13316             richards town      4 BHK       3600   5.0  400.00
13317     raja rajeshwari nagar      2 BHK       1141   2.0   60.00
13318           padmanabhanagar      4 BHK       4689   4.0  488.00
13319              doddathoguru      1 BHK        550   1.0   17.00

[13320 rows x 5 columns]

In [5]:
df2.isnull().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [6]:
df2.dropna(inplace=True)
final=df2

In [7]:
final=df2

In [8]:
l=[]
for i in final['size']:
    l.append(int(i[0]))

In [9]:
for i in l:
    if isinstance(i , str):
        print(i)

In [10]:
final['size']=l

In [11]:
final

                       location  size total_sqft  bath   price
0      electronic city phase ii     2       1056   2.0   39.07
1              chikka tirupathi     4       2600   5.0  120.00
2                   uttarahalli     3       1440   2.0   62.00
3            lingadheeranahalli     3       1521   3.0   95.00
4                      kothanur     2       1200   2.0   51.00
...                         ...   ...        ...   ...     ...
13315                whitefield     5       3453   4.0  231.00
13316             richards town     4       3600   5.0  400.00
13317     raja rajeshwari nagar     2       1141   2.0   60.00
13318           padmanabhanagar     4       4689   4.0  488.00
13319              doddathoguru     1        550   1.0   17.00

[13246 rows x 5 columns]

In [12]:
final['bath'].unique()

array([ 2.,  5.,  3.,  4.,  6.,  1.,  9.,  8.,  7., 11., 10., 14., 27.,
       12., 16., 40., 15., 13., 18.])

In [13]:
final[final['bath']>10]

                            location  size total_sqft  bath   price
938               5th phase jp nagar     9       1260  11.0   290.0
1078                   btm 1st stage     9       3300  14.0   500.0
1718       2electronic city phase ii     2       8000  27.0   230.0
1768              1 ramamurthy nagar     1       1200  11.0   170.0
1953                        kr puram     8       1200  12.0   110.0
1979                     hongasandra     8        990  12.0   120.0
3096            jp nagar 8th phase .     1      12000  12.0   525.0
3379                  1hanuman nagar     1       2000  16.0   490.0
3609   koramangala industrial layout     1      10000  16.0   550.0
4684                     munnekollal     4       2400  40.0   660.0
4916                   1channasandra     1       1250  15.0   125.0
6937            5th block hbr layout     9       2600  12.0   675.0
7979                   1 immadihalli     1       6000  12.0   150.0
8106                   wilson garden     8       1850  12.0   300.0
8636                  neeladri nagar     1       4000  12.0   160.0
9935                   1hoysalanagar     1       5425  13.0   275.0
10695                electronic city     9       1200  13.0   150.0
11128                         jigani     1       1200  11.0   105.0
11559                  1kasavanhalli     1       1200  18.0   200.0
13067                 defence colony     1       7150  13.0  3600.0

In [14]:
x=final[final.bath>15]
x

                            location  size total_sqft  bath  price
1718       2electronic city phase ii     2       8000  27.0  230.0
3379                  1hanuman nagar     1       2000  16.0  490.0
3609   koramangala industrial layout     1      10000  16.0  550.0
4684                     munnekollal     4       2400  40.0  660.0
11559                  1kasavanhalli     1       1200  18.0  200.0

In [15]:
def is_float(x):
   try:
         float(x)
   except:
        return False
   return True

In [16]:
final[final['total_sqft'].apply(is_float)==False]

                 location  size   total_sqft  bath    price
30              yelahanka     4  2100 - 2850   4.0  186.000
122                hebbal     4  3067 - 8156   4.0  477.000
137    8th phase jp nagar     2  1042 - 1105   2.0   54.005
165              sarjapur     2  1145 - 1340   2.0   43.490
188              kr puram     2  1015 - 1540   2.0   56.800
...                   ...   ...          ...   ...      ...
12975          whitefield     2   850 - 1060   2.0   38.190
12990      talaghattapura     3  1804 - 2273   3.0  122.000
13059              harlur     2  1200 - 1470   2.0   72.760
13265               hoodi     2  1133 - 1384   2.0   59.135
13299          whitefield     4  2830 - 2882   5.0  154.500

[190 rows x 5 columns]

In [17]:
def convert(x):
    t=x.split('-')
    if len(t)==2:
        return (float(t[0])+float(t[1]))/2
    try:
        return float(x)
    except:
        return None

In [18]:
a=final.copy()

In [19]:
a['total_sqft']=a['total_sqft'].apply(convert)

In [20]:
a[a['total_sqft'].apply(is_float)==False]

Empty DataFrame
Columns: [location, size, total_sqft, bath, price]
Index: []

In [21]:
a

                       location  size  total_sqft  bath   price
0      electronic city phase ii     2      1056.0   2.0   39.07
1              chikka tirupathi     4      2600.0   5.0  120.00
2                   uttarahalli     3      1440.0   2.0   62.00
3            lingadheeranahalli     3      1521.0   3.0   95.00
4                      kothanur     2      1200.0   2.0   51.00
...                         ...   ...         ...   ...     ...
13315                whitefield     5      3453.0   4.0  231.00
13316             richards town     4      3600.0   5.0  400.00
13317     raja rajeshwari nagar     2      1141.0   2.0   60.00
13318           padmanabhanagar     4      4689.0   4.0  488.00
13319              doddathoguru     1       550.0   1.0   17.00

[13246 rows x 5 columns]

In [22]:
final=a
final

                       location  size  total_sqft  bath   price
0      electronic city phase ii     2      1056.0   2.0   39.07
1              chikka tirupathi     4      2600.0   5.0  120.00
2                   uttarahalli     3      1440.0   2.0   62.00
3            lingadheeranahalli     3      1521.0   3.0   95.00
4                      kothanur     2      1200.0   2.0   51.00
...                         ...   ...         ...   ...     ...
13315                whitefield     5      3453.0   4.0  231.00
13316             richards town     4      3600.0   5.0  400.00
13317     raja rajeshwari nagar     2      1141.0   2.0   60.00
13318           padmanabhanagar     4      4689.0   4.0  488.00
13319              doddathoguru     1       550.0   1.0   17.00

[13246 rows x 5 columns]

In [23]:
final['pps']=final['price']*100000/final['total_sqft']

In [24]:
final['location']=df.location

In [25]:
final

                       location  size  total_sqft  bath   price           pps
0      electronic city phase ii     2      1056.0   2.0   39.07   3699.810606
1              chikka tirupathi     4      2600.0   5.0  120.00   4615.384615
2                   uttarahalli     3      1440.0   2.0   62.00   4305.555556
3            lingadheeranahalli     3      1521.0   3.0   95.00   6245.890861
4                      kothanur     2      1200.0   2.0   51.00   4250.000000
...                         ...   ...         ...   ...     ...           ...
13315                whitefield     5      3453.0   4.0  231.00   6689.834926
13316             richards town     4      3600.0   5.0  400.00  11111.111111
13317     raja rajeshwari nagar     2      1141.0   2.0   60.00   5258.545136
13318           padmanabhanagar     4      4689.0   4.0  488.00  10407.336319
13319              doddathoguru     1       550.0   1.0   17.00   3090.909091

[13246 rows x 6 columns]

In [26]:
final.location = final.location.apply(lambda x: x.strip())

In [27]:
final.location.unique()

array(['electronic city phase ii', 'chikka tirupathi', 'uttarahalli', ...,
       '12th cross srinivas nagar banshankari 3rd stage',
       'havanur extension', 'abshot layout'], shape=(1282,), dtype=object)

In [28]:
ls=final.groupby('location')['location'].count().sort_values(ascending=True)

In [29]:
ls.head(20)

location
2nd phase jp nagar, jp nagar                    1
3rd block hbr layout                            1
vittal mallya road                              1
viviani road                                    1
wajid layout thanisandra                        1
west of chord road                              1
wheelers road                                   1
whietfield,                                     1
1hanuman nagar                                  1
1hoysalanagar                                   1
1kasavanhalli                                   1
1st stage domlur                                1
1st stage radha krishna layout                  1
2 bedroom furnished farm house in kolar road    1
2electronic city phase ii                       1
2nd block hbr layout                            1
grihalakshmi layout                             1
gubbi cross, hennur main road                   1
gulakamale                                      1
1 immadihalli                                   1
Name: location, dtype: int64

In [30]:
len(ls[ls<=10])

1041

In [31]:
ls10=ls[ls<=10]
ls10

location
2nd phase jp nagar, jp nagar     1
3rd block hbr layout             1
vittal mallya road               1
viviani road                     1
wajid layout thanisandra         1
                                ..
nagappa reddy layout            10
kalkere                         10
sector 1 hsr layout             10
basapura                        10
sadashiva nagar                 10
Name: location, Length: 1041, dtype: int64

In [32]:
final.location = final.location.apply( lambda x: "other" if x in ls10 else x)

In [33]:
len(final.location.unique())

242

In [34]:
final['pps'].quantile(0.999)

np.float64(50959.580419581405)

In [35]:
final.describe()

               size    total_sqft          bath         price           pps
count  13246.000000  13200.000000  13246.000000  13246.000000  1.320000e+04
mean       2.778046   1555.302783      2.692586    112.389392  7.920759e+03
std        1.170077   1237.323445      1.341506    149.076587  1.067272e+05
min        1.000000      1.000000      1.000000      8.000000  2.678298e+02
25%        2.000000   1100.000000      2.000000     50.000000  4.267701e+03
50%        3.000000   1275.000000      2.000000     72.000000  5.438331e+03
75%        3.000000   1672.000000      3.000000    120.000000  7.317073e+03
max        9.000000  52272.000000     40.000000   3600.000000  1.200000e+07

In [36]:
final2=final[final.total_sqft/final['size']>=300]

In [37]:
final2

                       location  size  total_sqft  bath   price           pps
0      electronic city phase ii     2      1056.0   2.0   39.07   3699.810606
1              chikka tirupathi     4      2600.0   5.0  120.00   4615.384615
2                   uttarahalli     3      1440.0   2.0   62.00   4305.555556
3            lingadheeranahalli     3      1521.0   3.0   95.00   6245.890861
4                      kothanur     2      1200.0   2.0   51.00   4250.000000
...                         ...   ...         ...   ...     ...           ...
13315                whitefield     5      3453.0   4.0  231.00   6689.834926
13316                     other     4      3600.0   5.0  400.00  11111.111111
13317     raja rajeshwari nagar     2      1141.0   2.0   60.00   5258.545136
13318           padmanabhanagar     4      4689.0   4.0  488.00  10407.336319
13319              doddathoguru     1       550.0   1.0   17.00   3090.909091

[12472 rows x 6 columns]

In [38]:
final2.describe()

               size    total_sqft          bath         price            pps
count  12472.000000  12472.000000  12472.000000  12472.000000   12472.000000
mean       2.639112   1590.579998      2.576732    111.394903    6321.224286
std        0.946938   1261.028999      1.187855    152.346877    4188.395933
min        1.000000    300.000000      1.000000      9.000000     267.829813
25%        2.000000   1116.000000      2.000000     49.000000    4210.526316
50%        3.000000   1300.000000      2.000000     70.000000    5295.544522
75%        3.000000   1700.000000      3.000000    115.000000    6929.522602
max        9.000000  52272.000000     40.000000   3600.000000  176470.588235

In [39]:
final3=final2[final2['bath']<14]

In [40]:
min=final3.pps.quantile(0.003)
min

np.float64(2086.3030303030305)

In [41]:
max=final3.pps.quantile(0.93)
max

np.float64(11714.99510230736)

In [42]:
final4=final3[(final3.pps>min) & (final3.pps<max)]

In [43]:
final4

                       location  size  total_sqft  bath   price           pps
0      electronic city phase ii     2      1056.0   2.0   39.07   3699.810606
1              chikka tirupathi     4      2600.0   5.0  120.00   4615.384615
2                   uttarahalli     3      1440.0   2.0   62.00   4305.555556
3            lingadheeranahalli     3      1521.0   3.0   95.00   6245.890861
4                      kothanur     2      1200.0   2.0   51.00   4250.000000
...                         ...   ...         ...   ...     ...           ...
13315                whitefield     5      3453.0   4.0  231.00   6689.834926
13316                     other     4      3600.0   5.0  400.00  11111.111111
13317     raja rajeshwari nagar     2      1141.0   2.0   60.00   5258.545136
13318           padmanabhanagar     4      4689.0   4.0  488.00  10407.336319
13319              doddathoguru     1       550.0   1.0   17.00   3090.909091

[11554 rows x 6 columns]

In [44]:
x = pd.get_dummies(final4['location'], drop_first=True,dtype='int')

In [45]:
x

,1st phase jp nagar,2nd phase judicial layout,2nd stage nagarbhavi,5th block hbr layout,5th phase jp nagar,6th phase jp nagar,7th phase jp nagar,8th phase jp nagar,9th phase jp nagar,abbigere,...,vijayanagar,vishveshwarya layout,vishwapriya layout,vittasandra,whitefield,yelachenahalli,yelahanka,yelahanka new town,yelenahalli,yeshwanthpur
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13315,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
13316,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13317,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13318,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13319,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [46]:
final5=pd.concat([final4,x],axis='columns')

In [47]:
final5

,location,size,total_sqft,bath,price,pps,1st phase jp nagar,2nd phase judicial layout,2nd stage nagarbhavi,5th block hbr layout,...,vijayanagar,vishveshwarya layout,vishwapriya layout,vittasandra,whitefield,yelachenahalli,yelahanka,yelahanka new town,yelenahalli,yeshwanthpur
0,electronic city phase ii,2,1056.0,2.0,39.07,3699.810606,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,chikka tirupathi,4,2600.0,5.0,120.00,4615.384615,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,uttarahalli,3,1440.0,2.0,62.00,4305.555556,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,lingadheeranahalli,3,1521.0,3.0,95.00,6245.890861,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,kothanur,2,1200.0,2.0,51.00,4250.000000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13315,whitefield,5,3453.0,4.0,231.00,6689.834926,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
13316,other,4,3600.0,5.0,400.00,11111.111111,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13317,raja rajeshwari nagar,2,1141.0,2.0,60.00,5258.545136,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13318,padmanabhanagar,4,4689.0,4.0,488.00,10407.336319,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13319,doddathoguru,1,550.0,1.0,17.00,3090.909091,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [48]:
from sklearn.linear_model import LinearRegression as lr
model=lr()

In [49]:
input=final5.drop(['price','pps','location'],axis='columns')
target=final5['price']

In [50]:
from sklearn.model_selection import train_test_split as tts

In [51]:
x1,x2,y1,y2=tts(input,target,test_size=0.2)

In [52]:
model.fit(x1,y1)

LinearRegression()

In [53]:
model.score(x2,y2)

0.8320443962848997

In [54]:
model.score(x1,y1)

0.8128337683003439

In [55]:
model.score(input,target)

0.8174594869455163

In [56]:
from sklearn.model_selection import ShuffleSplit as ss
from sklearn.model_selection import cross_val_score as cvs

In [57]:
cv=ss(n_splits=5, test_size=0.2, random_state=0)

score=cvs(lr(), input, target, cv=cv)

In [58]:
score.mean()

np.float64(0.8260695560396748)

In [59]:
from sklearn.model_selection import GridSearchCV as gscv 
from sklearn.linear_model import Lasso 
from sklearn.tree import DecisionTreeRegressor as dtr

In [60]:
def bestmodel(input,target):
    algos={
        'lr':{
            'model':lr(),
            'parmas':{
                'fit_intercept':[True,False],
            }
        },
        'lasso':{
            'model': Lasso(),
            'parmas':{
                'alpha':[1,2,3,4,5],
                'selection':['cyclic','random']
            }
        },
        'dtr':{
            'model':dtr(),
            'parmas':{
                'splitter':['best','random'],
                'max_depth':[2,3,4,5,6,7,8,9,10],
            }   
        }  
        }
    scores=[]
    for a,c in algos.items():
        gs=gscv(c['model'],c['parmas'],cv=cv)
        gs.fit(input,target)
        scores.append({
            'model':a,
            'best_score':gs.best_score_,
            'best_params':gs.best_params_
            })
    return pd.DataFrame(scores,columns=['model','best_score','best_params'])

In [61]:
bestmodel(input,target)

   model  best_score                           best_params
0     lr    0.826229              {'fit_intercept': False}
1  lasso    0.800051   {'alpha': 1, 'selection': 'random'}
2    dtr    0.798530  {'max_depth': 7, 'splitter': 'best'}

In [62]:
model.score(x2,y2)

0.8320443962848997

In [63]:
import pickle

with open('model.pickle','wb') as f:
    pickle.dump(model,f)

In [64]:
with open('model.pickle','rb') as f:
    model= pickle.load(f)

model

LinearRegression()

In [65]:
model.score(input,target)

0.8174594869455163

In [66]:
np.where(input)

(array([    0,     0,     0, ..., 11553, 11553, 11553], shape=(46213,)),
 array([ 0,  1,  2, ...,  1,  2, 75], shape=(46213,)))

In [67]:
y_predicted=model.predict(input)

In [68]:
pd.DataFrame( y_predicted, target )

                 0
price
39.07    35.059069
120.00  107.013698
62.00    61.165713
95.00    97.090704
51.00    58.958315
...            ...
231.00  230.295910
400.00  249.112728
60.00    44.127905
488.00  337.999701
17.00     6.865689

[11554 rows x 1 columns]

In [69]:
input.columns

Index(['size', 'total_sqft', 'bath', '1st phase jp nagar',
       '2nd phase judicial layout', '2nd stage nagarbhavi',
       '5th block hbr layout', '5th phase jp nagar', '6th phase jp nagar',
       '7th phase jp nagar',
       ...
       'vijayanagar', 'vishveshwarya layout', 'vishwapriya layout',
       'vittasandra', 'whitefield', 'yelachenahalli', 'yelahanka',
       'yelahanka new town', 'yelenahalli', 'yeshwanthpur'],
      dtype='object', length=243)

In [71]:
np.where(input.columns=='2nd stage nagarbhavi')[0][0]

np.int64(5)

In [72]:
a=input.head(1)

In [73]:
a.shape

(1, 243)

In [74]:
model.predict(a)

array([35.05906908])

In [75]:
target

0         39.07
1        120.00
2         62.00
3         95.00
4         51.00
          ...
13315    231.00
13316    400.00
13317     60.00
13318    488.00
13319     17.00
Name: price, Length: 11554, dtype: float64

In [76]:
def predictp(location,s, total_sqft, bath):
    lx=np.where(input.columns==location)[0][0]
    x=np.zeros(len(input.columns))
    x[0]=s
    x[1]=total_sqft
    x[2]=bath
    if lx>=0:
        x[lx]=1
    b = pd.DataFrame(np.array([x],dtype='int'), columns=input.columns)
    result = model.predict(b)

    return result[0]

In [78]:
predictp("1st phase jp nagar", 2 , 1056, 2)

np.float64(88.59477327059233)

In [ ]:
predictp("1st Phase JP Nagar", 4	,2825.0,	4.0)

np.float64(221.04376589357292)

In [79]:
target[936]

np.float64(250.0)

In [80]:
with open('model.pickle','wb') as f:
    pickle.dump(model,f)

In [81]:
with open('model.pickle','rb') as f:
    model=pickle.load(f)

In [82]:
model

LinearRegression()

In [83]:
import json
columns={'data_columns':[col.lower() for col in input.columns]}

with open("columns.json", "w") as f:
    f.write(json.dumps(columns))